name: Web Extension CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: npm run package
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/danmaku-flow-for-youtube-${{ github.ref_name }}.zip
